version: "3.8"
services:
  mariadb:
    image: library/mariadb:10.5
    container_name: mysql-game-community-bot
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - db.env
    ports:
      - "9002:3306"
  vladimir-bot:
    build: ./
    container_name: game-community-bot
    env_file:
      - app.env
    depends_on:
      - mariadb
    ports:
      - "9001:8080"
    links:
      - mariadb
